//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Process.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ProcessParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IProcessListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProcessParser.process"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcess([NotNull] ProcessParser.ProcessContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProcessParser.process"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcess([NotNull] ProcessParser.ProcessContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProcessParser.initProcess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitProcess([NotNull] ProcessParser.InitProcessContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProcessParser.initProcess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitProcess([NotNull] ProcessParser.InitProcessContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProcessParser.objectWithProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObjectWithProperty([NotNull] ProcessParser.ObjectWithPropertyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProcessParser.objectWithProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObjectWithProperty([NotNull] ProcessParser.ObjectWithPropertyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProcessParser.objectProperties"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObjectProperties([NotNull] ProcessParser.ObjectPropertiesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProcessParser.objectProperties"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObjectProperties([NotNull] ProcessParser.ObjectPropertiesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProcessParser.property"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProperty([NotNull] ProcessParser.PropertyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProcessParser.property"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProperty([NotNull] ProcessParser.PropertyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProcessParser.chainOfCommands"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChainOfCommands([NotNull] ProcessParser.ChainOfCommandsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProcessParser.chainOfCommands"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChainOfCommands([NotNull] ProcessParser.ChainOfCommandsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProcessParser.simplecommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimplecommand([NotNull] ProcessParser.SimplecommandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProcessParser.simplecommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimplecommand([NotNull] ProcessParser.SimplecommandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProcessParser.conditioncommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditioncommand([NotNull] ProcessParser.ConditioncommandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProcessParser.conditioncommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditioncommand([NotNull] ProcessParser.ConditioncommandContext context);
}
