//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Process.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IProcessListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class ProcessBaseListener : IProcessListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProcessParser.process"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProcess([NotNull] ProcessParser.ProcessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProcessParser.process"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProcess([NotNull] ProcessParser.ProcessContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProcessParser.initProcess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInitProcess([NotNull] ProcessParser.InitProcessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProcessParser.initProcess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInitProcess([NotNull] ProcessParser.InitProcessContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProcessParser.objectWithProperty"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjectWithProperty([NotNull] ProcessParser.ObjectWithPropertyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProcessParser.objectWithProperty"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjectWithProperty([NotNull] ProcessParser.ObjectWithPropertyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProcessParser.objectProperties"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjectProperties([NotNull] ProcessParser.ObjectPropertiesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProcessParser.objectProperties"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjectProperties([NotNull] ProcessParser.ObjectPropertiesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProcessParser.property"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProperty([NotNull] ProcessParser.PropertyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProcessParser.property"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProperty([NotNull] ProcessParser.PropertyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProcessParser.chainOfCommands"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterChainOfCommands([NotNull] ProcessParser.ChainOfCommandsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProcessParser.chainOfCommands"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitChainOfCommands([NotNull] ProcessParser.ChainOfCommandsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProcessParser.simplecommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimplecommand([NotNull] ProcessParser.SimplecommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProcessParser.simplecommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimplecommand([NotNull] ProcessParser.SimplecommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProcessParser.conditioncommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditioncommand([NotNull] ProcessParser.ConditioncommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProcessParser.conditioncommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditioncommand([NotNull] ProcessParser.ConditioncommandContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
